version: '3.9'
services: 
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    api:
        build: .
        ports:
            - "4000:4000"
        environment:
            PORT: 4000
            MONGO_DB_URI: "mongodb://mongo:27017"
            DB_NAME: "phones"
        depends_on:
            - mongo
volumes: 
    mongo_data: {}