apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/graphql-server-example-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DB_NAME
              value: phones
            - name: MONGO_DB_URI
              value: mongodb://mongo:27017
            - name: PORT
              value: "4000"
          image: api
          name: api
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
